# Form implementation generated from reading ui file '.\Home - Copy.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(780, 550)
        MainWindow.setMinimumSize(QtCore.QSize(780, 550))
        MainWindow.setStyleSheet("padding: 0px;\n"
"border: 0px;\n"
"background-color: white;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setStyleSheet("max-width: 50px;\n"
"background-color: white;\n"
"border-radius: 15px;\n"
"border: 3px solid black;\n"
"padding: 0px;\n"
"margin: 5px;")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("min-height: 34px;\n"
"min-width: 31px;\n"
"border: 2px solid black;\n"
"border-radius: 18px;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setStyleSheet("border: 0px;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("max-height: 22px;\n"
"border: 2px solid black;\n"
"padding: 6px;\n"
"border-radius: 18px;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(".\\../Image/home_a.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"    max-height: 22px;\n"
"    border: 2px solid white;\n"
"    padding: 6px;\n"
"    border-radius: 18px;\n"
"}\n"
"\n"
"QLabel:hover{\n"
"    max-height: 22px;\n"
"    border: 2px solid gray;\n"
"    padding: 6px;\n"
"    border-radius: 18px;\n"
"}")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(".\\../Image/notes_d.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"    max-height: 22px;\n"
"    border: 2px solid white;\n"
"    padding: 6px;\n"
"    border-radius: 18px;\n"
"}\n"
"\n"
"QLabel:hover{\n"
"    max-height: 22px;\n"
"    border: 2px solid gray;\n"
"    padding: 6px;\n"
"    border-radius: 18px;\n"
"}")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(".\\../Image/chat_d.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel{\n"
"    max-height: 22px;\n"
"    border: 2px solid white;\n"
"    padding: 6px;\n"
"    border-radius: 18px;\n"
"}\n"
"\n"
"QLabel:hover{\n"
"    max-height: 22px;\n"
"    border: 2px solid gray;\n"
"    padding: 6px;\n"
"    border-radius: 18px;\n"
"}")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(".\\../Image/about_b.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setStyleSheet("padding: 0px;\n"
"border: 0px;")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_5 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_5.setStyleSheet("margin-top: 20px;\n"
"min-height: 150px;\n"
"max-height: 150px;")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_7 = QtWidgets.QLabel(parent=self.widget_5)
        self.label_7.setStyleSheet("max-width: 120px;\n"
"min-width: 120px;\n"
"max-height: 120px;\n"
"min-height: 120px;")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(".\\../Image/welcome.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.widget_6 = QtWidgets.QWidget(parent=self.widget_5)
        self.widget_6.setStyleSheet("max-height: 120px;\n"
"min-height: 120px;")
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.widget_6)
        self.textBrowser.setStyleSheet("min-width: 250px;")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_3.addWidget(self.textBrowser)
        self.horizontalLayout_2.addWidget(self.widget_6)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.widget_5)
        self.widget_4 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_3 = QtWidgets.QWidget(parent=self.widget_4)
        self.widget_3.setStyleSheet("border: 2px solid black;\n"
"border-radius: 20px;\n"
"margin: 10px;\n"
"max-width: 260%;")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_7 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_7.setStyleSheet("border: 0px;\n"
"margin-bottom: 0px;")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_8.setStyleSheet("max-width: 50px;\n"
"max-height: 50px;")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(".\\../Image/todo.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(parent=self.widget_7)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.verticalLayout_4.addWidget(self.widget_7)
        self.listWidget = QtWidgets.QListWidget(parent=self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("QListWidget{\n"
"    border: 0px;\n"
"    margin-top: 0px;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    height: 35px;\n"
"}\n"
"\n"
"QListWidget::item::hover{\n"
"    height: 35px;\n"
"    background-color: white;\n"
"    color: black;\n"
"}\n"
"\n"
"QListWidget::item::pressed{\n"
"    height: 35px;\n"
"    background-color: white;\n"
"    color: black;\n"
"}\n"
"\n"
"QListWidget::item::selected{\n"
"    height: 35px;\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 0px;\n"
"}")
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemFlag.ItemIsUserCheckable|QtCore.Qt.ItemFlag.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.CheckState.Unchecked)
        self.listWidget.addItem(item)
        self.verticalLayout_4.addWidget(self.listWidget)
        self.widget_10 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_10.setStyleSheet("border: 0px;")
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.widget_10)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    border: 2px solid black;\n"
"    height: 30px;\n"
"    border-radius: 10px;\n"
"    background-color: #FFCE41;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    border: 3px solid black;\n"
"    height: 30px;\n"
"    border-radius: 10px;\n"
"    background-color: #FFCE41;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border: 3px solid black;\n"
"    height: 30px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(234, 188, 59);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../Image/new.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_7.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.widget_10)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    border: 2px solid black;\n"
"    height: 30px;\n"
"    border-radius: 10px;\n"
"    background-color: #FFCE41;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    border: 3px solid black;\n"
"    height: 30px;\n"
"    border-radius: 10px;\n"
"    background-color: #FFCE41;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border: 3px solid black;\n"
"    height: 30px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(234, 188, 59);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\../Image/remove.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_7.setIcon(icon1)
        self.pushButton_7.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_7.addWidget(self.pushButton_7)
        self.verticalLayout_4.addWidget(self.widget_10)
        self.horizontalLayout_5.addWidget(self.widget_3)
        self.widget_8 = QtWidgets.QWidget(parent=self.widget_4)
        self.widget_8.setStyleSheet("border: 2px solid black;\n"
"border-radius: 20px;\n"
"margin: 10px;")
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_9 = QtWidgets.QWidget(parent=self.widget_8)
        self.widget_9.setStyleSheet("border: 0px;\n"
"margin-bottom: 0px;")
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(parent=self.widget_9)
        self.label_10.setStyleSheet("max-width: 50px;\n"
"max-height: 50px;")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(".\\../Image/all_note.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(parent=self.widget_9)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.verticalLayout_5.addWidget(self.widget_9)
        self.listWidget_2 = QtWidgets.QListWidget(parent=self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.listWidget_2.setFont(font)
        self.listWidget_2.setStyleSheet("QListWidget{\n"
"    border: 0px;\n"
"    margin-top: 0px;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    height: 35px;\n"
"    margin: 5px;\n"
"}")
        self.listWidget_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.listWidget_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.verticalLayout_5.addWidget(self.listWidget_2)
        self.widget_11 = QtWidgets.QWidget(parent=self.widget_8)
        self.widget_11.setStyleSheet("border: 0px;")
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget_11)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border: 2px solid black;\n"
"    height: 30px;\n"
"    border-radius: 10px;\n"
"    background-color: #FFCE41;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    border: 3px solid black;\n"
"    height: 30px;\n"
"    border-radius: 10px;\n"
"    background-color: #FFCE41;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border: 3px solid black;\n"
"    height: 30px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(234, 188, 59);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\../Image/all_note_view.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(18, 16))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_8.addWidget(self.pushButton_2)
        self.verticalLayout_5.addWidget(self.widget_11)
        self.horizontalLayout_5.addWidget(self.widget_8)
        self.verticalLayout.addWidget(self.widget_4)
        self.horizontalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "U"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Segoe UI \';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI \'; font-size:16pt; font-weight:600;\">Vasper Jance</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Segoe UI \'; font-size:8pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI \'; font-size:14pt;\">Welcome back, we\'ve missed your smiling face!</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "Todo list"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_6.setText(_translate("MainWindow", " New Task"))
        self.pushButton_7.setText(_translate("MainWindow", " Remove"))
        self.label_11.setText(_translate("MainWindow", "Notes"))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("MainWindow", "Google Gemini API - Google AI Studio"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("MainWindow", "Google Calendar - How to use it?"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.pushButton_2.setText(_translate("MainWindow", " View All"))
