# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(655, 510)
        MainWindow.setMinimumSize(QtCore.QSize(655, 510))
        MainWindow.setMaximumSize(QtCore.QSize(655, 1000))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(340, 180, 281, 51))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"    padding: 10px;\n"
"    border: 2px solid rgb(214, 214, 214);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    padding: 10px;\n"
"    border: 2px solid gray;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    padding: 10px;\n"
"    border: 2px solid gray;\n"
"    border-radius: 20px;\n"
"}")
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 150, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(290, 60, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(275, 410, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"    border: 1px solid #faae2b;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: transparent;\n"
"    border: 2px solid #faae2b;\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(225, 480, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(370, 480, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(3, 148, 252);")
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 10, 151, 151))
        self.label_4.setStyleSheet("background-color: transparent;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../Image/OIG-removebg-preview.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(280, 380, 111, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 180, 281, 51))
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"    padding: 10px;\n"
"    border: 2px solid rgb(214, 214, 214);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    padding: 10px;\n"
"    border: 2px solid gray;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    padding: 10px;\n"
"    border: 2px solid gray;\n"
"    border-radius: 20px;\n"
"}")
        self.lineEdit_3.setInputMask("")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 150, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 260, 280, 90))
        self.label.setStyleSheet("background-color: red;\n"
"padding: 15px;\n"
"border-radius: 20px;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../captcha.png"))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(350, 270, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(340, 300, 281, 51))
        self.lineEdit_4.setStyleSheet("QLineEdit{\n"
"    padding: 10px;\n"
"    border: 2px solid rgb(214, 214, 214);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    padding: 10px;\n"
"    border: 2px solid gray;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    padding: 10px;\n"
"    border: 2px solid gray;\n"
"    border-radius: 20px;\n"
"}")
        self.lineEdit_4.setInputMask("")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_4.setObjectName("lineEdit_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Password"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.label_5.setText(_translate("MainWindow", "Welcome"))
        self.pushButton.setText(_translate("MainWindow", "Login"))
        self.label_6.setText(_translate("MainWindow", "Do not have an account?"))
        self.label_7.setText(_translate("MainWindow", "Register now"))
        self.checkBox.setText(_translate("MainWindow", "Keep me login"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Email"))
        self.label_8.setText(_translate("MainWindow", "Email"))
        self.label_3.setText(_translate("MainWindow", "Captcha"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Captcha"))
